### ISSUE TITLE
Failure to precompile

### ISSUE THREAD

**Issue by charleskawczynski** [JuliaSIMD/PolyesterWeave.jl#17]
It looks like https://github.com/JuliaSIMD/PolyesterWeave.jl/commit/93613fb561b3168509c2901e8fa82b1162629c1b was a breaking change (as suggested [here](https://github.com/JuliaSIMD/PolyesterWeave.jl/commit/93613fb561b3168509c2901e8fa82b1162629c1b#diff-dbb51e83936b188df660b90c59f451d64d6f6544234699c316e649efd0c0f375L32)) and only the patch version was changed, I'm seeing failure to precompile FastBroadcast in a package that indirectly depends on PolyesterWeave.jl:

```
ERROR: The following 5 dependencies failed to precompile:
 
FastBroadcast [7034ab61-46d4-4ed7-9d0f-46aef9175898]
 
Failed to precompile FastBroadcast [7034ab61-46d4-4ed7-9d0f-46aef9175898] to /scratch/depot/cpu/compiled/v1.8/FastBroadcast/jl_uc7ouY.
ERROR: LoadError: UndefVarError: num_threads not defined
```

**Comment by chriselrod** [comment]
Thanks for the issue.
Broken version yanked: https://github.com/JuliaRegistries/General/pull/75041
Fix: https://github.com/JuliaSIMD/PolyesterWeave.jl/commit/0dcdafd898d76fd3ec31e6bcdc89b9a187a5d250

**Comment by charleskawczynski** [comment]
Thank you!
